[[Rift]]
arch = "x86_64"
git-tree-sha1 = "ea7aafdd6abd090aef58da90e3f5c7b4bff2fe4b"
libc = "glibc"
os = "linux"
rr_softticks = "1"

    [[Rift.download]]
    sha256 = "2008ff509d6e23e8e36812c151dca59bd1768b3da64a30efbeba6c90d1cd011a"
    url = "https://api.github.com/repos/ChronitonAI/rift/releases/assets/606594241"
