[[Rift]]
arch = "x86_64"
git-tree-sha1 = "91cb24ebe578d1e2736062dfbace8ab05ce1d3b6"
libc = "glibc"
os = "linux"
rr_softticks = "1"

    [[Rift.download]]
    sha256 = "ec6b87ecdddec57e46beee21631808e43940ec478baaf71ea89c3ffab96879dc"
    url = "https://api.github.com/repos/ChronitonAI/rift/releases/assets/606513436"
