version = "0.1.0"
format_version = "1.0"
name = "Rift"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "Rift"
platform = "x86_64-linux-gnu-rr_softticks+1"
deps = []
lazy = "false"
src_version = "0.1.0"

    [builds.artifact]
    treehash = "sha1:e77ae2fff99d6776e6777bd958d2faad25786b49"
    download_sources = []

    [[builds.licenses]]
    filename = "NOTICE"
    license_text = """rift: https://github.com/ChronitonAI/rift (bundles the Julia runtime, MIT licensed)\n"""

    [[builds.products]]
    path = "bin/rift"
    type = "executable"
    name = "rift"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:7bb56db7009ebee538e34d72979eda9e18ed930b"
    download_sources = []

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:214213be013b78fae4bd6ed80a30415aba4c748b"
    download_sources = []

    [[builds.sources]]
    treehash = "sha1:188806324b4c3a138e4af88c22db235119f5d3e2"
    url = "https://api.github.com/repos/ChronitonAI/rift/releases/assets/604619509"

    [builds.callback_defs]
