version = "0.1.1"
format_version = "1.0"
name = "Rift"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "Rift"
platform = "x86_64-linux-gnu-rr_softticks+1"
deps = []
lazy = "false"
src_version = "0.1.0"

    [builds.artifact]
    treehash = "sha1:3d47604d4c71d3834774a20b3875e40eba5c6444"
    download_sources = []

    [[builds.licenses]]
    filename = "NOTICE"
    license_text = """rift: https://github.com/ChronitonAI/rift (bundles the Julia runtime, MIT licensed)\n"""

    [[builds.products]]
    path = "bin/rift"
    type = "executable"
    name = "rift"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:828d9021402bd856431d4369a86430c74f8b882d"
    download_sources = []

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:77d33227833ea48c3ccf009ba116499293a96428"
    download_sources = []

    [[builds.sources]]
    treehash = "sha1:d2801088ed5474ff27336e7403d634d0514e630c"
    url = "https://api.github.com/repos/ChronitonAI/rift/releases/assets/606014740"

    [builds.callback_defs]
