version = "0.1.3"
format_version = "1.0"
name = "Rift"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "Rift"
platform = "x86_64-linux-gnu-rr_softticks+1"
deps = []
lazy = "false"
src_version = "0.1.0"

    [builds.artifact]
    treehash = "sha1:ea7aafdd6abd090aef58da90e3f5c7b4bff2fe4b"
    download_sources = []

    [[builds.licenses]]
    filename = "NOTICE"
    license_text = """rift: https://github.com/ChronitonAI/rift (bundles the Julia runtime, MIT licensed)\n"""

    [[builds.products]]
    path = "bin/rift"
    type = "executable"
    name = "rift"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4fc741e31f89f3c32fa10990e0acf1539631fc68"
    download_sources = []

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:a8110cab6c439bfcc21cdb8448a637d90716a90c"
    download_sources = []

    [[builds.sources]]
    treehash = "sha1:1a7febf4faff02de1084be63e4195b70dc9feb6c"
    url = "https://api.github.com/repos/ChronitonAI/rift/releases/assets/606590128"

    [builds.callback_defs]
